language: node_js
node_js:
  - "10"
script:
  - yarn --version
  - yarn lint
  - yarn test
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
    - packages/tests/base
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
