environment:
  nodejs_version: "10"

install:
  - yarn --version
  - ps: $env:APPVEYOR_CACHE_SKIP_RESTORE = "true"
  - ps: Install-Product node $env:nodejs_version
  - yarn --network-timeout 600000

test_script:
  - git --version
  - node --version
  - yarn --version
  - yarn test:win

build: off
